# for the time being, the model architecture only supports these arguments
PROCESSED_IMG_WIDTH = 128
PROCESSED_IMG_HEIGHT = 128

GRID_WIDTH = 16
GRID_HEIGHT = 16

MAX_GRID_ROW = PROCESSED_IMG_WIDTH//GRID_WIDTH
MAX_GRID_COLUMN = PROCESSED_IMG_HEIGHT//GRID_HEIGHT
